# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      diana:
        enabled: true
        generate_for:
          exclude:
            - test/
          include:
            - test/**/integration/*
            - test/**/integration/**/*

builders:
  diana:
    import: "package:diana/diana.dart"
    builder_factories: ["diana"]
    build_extensions: { ".dart": ["gql.dart"] }
    auto_apply: dependents
    build_to: source
